from pipeline_common import read_jsonl

r = next(read_jsonl('poison_pii_result.jsonl'))
print('poison_injected     :', r['retrieval']['poison_injected'] is not None)
print('poison_redacted (S6):', r['retrieval']['poison_redacted'])
print('sanitized_chunks has SSN pattern:', any('123-45-6789' in c for c in r['retrieval']['sanitized_chunks']))
print('ranked_chunks has SSN pattern   :', any('123-45-6789' in c for c in r['retrieval']['ranked_chunks']))
print()
print('generation.answer   :', r['generation']['answer'])
print('generation.disagreement:', r['generation']['disagreement'])
print()
print('grounding           :', r['grounding'])
print()
print('multivector          :', r['multivector'])
print()
print('output_sanitization :', r['output_sanitization'])
print('dlp                 :', r['dlp'])
print()
print('blocked             :', r['blocked'], '| stage:', r['block_stage'], '| reason:', r['block_reason'])
print('final_response      :', r['final_response'])
